### ISSUE TITLE
Failure in step "Clean up .Renviron"

### ISSUE THREAD

**Issue by GreatEmerald** [yihui/crandalf#13]
When trying to run the GitHub Action with the code as provided on my repository, I get this error:

```
Run sed -i '' /R_LIBS_USER/d .Renviron
sed: .Renviron: No such file or directory
Error: Process completed with exit code 1.
```

I guess it should check whether that file exists in the first place?

**Comment by yihui** [comment]
That's weird... It does exist: https://github.com/yihui/crandalf/blob/master/.Renviron and also exists in your fork: https://github.com/GreatEmerald/crandalf/blob/master/.Renviron

**Comment by GreatEmerald** [comment]
Yes, it works in the fork. I realised that you probably intended this to work by forking and then changing the name of the repository, rather than copying the yaml file to the repository that should be checked, which is what I assumed and did (as that's standard practice for GitHub actions, such as in r-lib/actions).

So this is more of a documentation issue, good to say in the readme that people using it should fork the repository :)

**Comment by yihui** [comment]
I mentioned in the second bullet that you could fork this repo: https://github.com/yihui/crandalf#timeout For an average user, I guess this shouldn't be necessary unless they have a large number of reverse dependencies to check. The tldr in readme should be enough for most people: https://github.com/yihui/crandalf#crandalf

I don't see any benefit of turning this repo into an action (it will actually make it slower to check packages because you wouldn't be able to share the large number of packages that I have already cached here in this repo).

**Comment by GreatEmerald** [comment]
Yes, but that bullet point seems to only be relevant when one runs into timeout problems, hence why I didn't see it. And I was mostly going off of the tl;dr section, but GitHub shows a big warning screen when clicking on the link saying that one does not have permissions to edit actions in this repository, with an option to fork it. So I suggest changing this part of the tl;dr:
> you can edit the Github Action rev-check.yaml
To something like:
> you can fork the repository by editing the Github Action rev-check.yaml
That makes it clear that the intended way to use it is to make a fork.

**Comment by yihui** [comment]
Good suggestion. Thank you!
